### ISSUE TITLE
Model not found in control net

### ISSUE THREAD

**Issue by mkyung** [houseofsecrets/SdPaint#13]
Hi! Im new to the controlNet stuff, not sure if I installed it correctly - I installed the extensions and downloaded the *.pth models into the `F:\dev\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models` but back to AUTOMATIC1111 it was still giving me the error, need some help:

```Error running process: F:\dev\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\dev\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\dev\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 752, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "F:\dev\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 513, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "F:\dev\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 528, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None```

**Comment by sasuniki** [comment]
i have this problem too

**Comment by unt-pics** [comment]
same here

**Comment by Hoasker** [comment]
I see the model name in the payload.json file. ( "model": "control_sd15_scribble [fef5e48e]")
I found this model here https://huggingface.co/lllyasviel/ControlNet/tree/main/models. Trying to run

**Comment by sasuniki** [comment]
> I see the model name in the payload.json file. ( "model": "control_sd15_scribble [fef5e48e]") I found this model here https://huggingface.co/lllyasviel/ControlNet/tree/main/models. Trying to run

where it needs to be moved to?

**Comment by unt-pics** [comment]
> > I see the model name in the payload.json file. ( "model": "control_sd15_scribble [fef5e48e]") I found this model here https://huggingface.co/lllyasviel/ControlNet/tree/main/models. Trying to run
> 
> where it needs to be moved to?

worked for me, here - 
stable-diffusion-webui-master\extensions\sd-webui-controlnet\models

**Comment by Hoasker** [comment]
> > > I see the model name in the payload.json file. ( "model": "control_sd15_scribble [fef5e48e]") I found this model here https://huggingface.co/lllyasviel/ControlNet/tree/main/models. Trying to run
> > 
> > 
> > where it needs to be moved to?
> 
> worked for me, here - stable-diffusion-webui-master\extensions\sd-webui-controlnet\models

Sorry I didn't see the question. This worked for me too

**Comment by mkyung** [comment]
Works for me too, thank you all. 
To summarize: 
I downloaded all models from both places:
https://huggingface.co/lllyasviel/ControlNet/tree/main/models
https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main

and dumped them into 
`<your computer>\stable-diffusion-webui\extensions\sd-webui-controlnet\models`

and it worked 👍

**Comment by masikh** [comment]
Save the script as a Python file (e.g., download_files.py) and run it. It will download the files to the current working directory if they don't already exist. The progress and status will be displayed in the console.

import os
import urllib.request

urls = [
    "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_canny.pth",
    "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_depth.pth",
    "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_hed.pth",
    "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_mlsd.pth",
    "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_normal.pth",
    "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_openpose.pth",
    "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_scribble.pth",
    "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_seg.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11e_sd15_ip2p.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11e_sd15_shuffle.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1p_sd15_depth.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_canny.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_inpaint.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_lineart.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_mlsd.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_normalbae.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_openpose.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_scribble.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_seg.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_softedge.pth",
    "https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15s2_lineart_anime.pth"
]

for url in urls:
    filename = url.split("/")[-1]
    if not os.path.exists(filename):
        print(f"Downloading {filename}...")
        urllib.request.urlretrieve(url, filename)
        print(f"{filename} downloaded successfully!")
    else:
        print(f"{filename} already exists. Skipping download.")
