### ISSUE TITLE
Instructions not clear.

### ISSUE THREAD

**Issue by CodeMonkey80** [houseofsecrets/SdPaint#15]
Where do the files have to be downloaded and where is Start.bat supposed to be launched from? 

I created a separate folder and when run it downloads all the necessary files but then cmd window closes and nothing is happening. I'm running A1111 with all requirements (--api and  "Allow other script to control this extension" enabled). Where is the scribble canvas supposed to appear?

**Comment by houseofsecrets** [comment]
I think you get an error and it closed.
You could try to start it from the command line and then you can see what error you get.
When in the sdpaint folder type cmd in the location bar and enter. You should get a command window.
Then type python Scripts/SdPaint.py and it wil start the program.
Post back what kind of error you get

**Comment by CodeMonkey80** [comment]
Thanks. The issue was with my version of Python not having tkinter installed. Problem has been resolved :)
