### ISSUE TITLE
How to allow other script to control the stable diffussion extension?

### ISSUE THREAD

**Issue by saaasquiish** [houseofsecrets/SdPaint#2]
On the "You also need to make sure the "Allow other script to control this extension" option is enabled in the settings of control net", I didn't see any setting for it, am I looking in the wrong place? I'm on http://127.0.0.1:7860/ and can't see it.

**Comment by adenek** [comment]
You will find it in the settings of automatic 1111 in the webui.

**Comment by Trolot** [comment]
I'm having trouble finding any relevant settings containing "scripts" "external" or "allow", where exactly should I be finding this setting and what is it called?

**Comment by houseofsecrets** [comment]
You can find it here. Let me know if that helps
![ScriptControl](https://user-images.githubusercontent.com/8179181/232762103-2645430a-39df-4999-bbb0-8ad61384ff50.png)

**Comment by BryceFuller** [comment]
@Trolot, which extension from the Available tab needs to be downloaded for the controlNet tab to be added to settings?

**Comment by Danamir** [comment]
The information is now available in the detailed installation instructions ( INSTALL_Windows.md ).
