### ISSUE TITLE
RuntimeError: model not found: None

### ISSUE THREAD

**Issue by FlashGun001** [houseofsecrets/SdPaint#23]
Hello
I'm having this issue when I start drawing using the SdPaint window.

Anyone know what's up and how to fix this?

![image](https://user-images.githubusercontent.com/16510825/233728897-31a8ffae-d3d5-4c59-9f16-502bfaa65d87.png)

**Comment by mkyung** [comment]
You can refer to my issue
https://github.com/houseofsecrets/SdPaint/issues/13

**Comment by Danamir** [comment]
The application has been updated to fetch the controlnet models from the API. Can you update it with `git pull` (or eventually by cloning the repository again if you have conflicts) and give it a try ?
