### ISSUE TITLE
Getting this error on Start.bat launch.

### ISSUE THREAD

**Issue by CodeMonkey80** [houseofsecrets/SdPaint#30]
![image](https://user-images.githubusercontent.com/37898238/234388109-4f910fbc-5715-4c08-aa9f-3d856ae5b062.png)

Start_img2img.bat launches fine.

Is my Python broken?

**Comment by Danamir** [comment]
There seems to be a typo in the `controlnet.json-dist` file : missing `,` after `"override_settings_restore_afterwards": "true"` line 20.

I will push a fix soon. You will have to correct or delete your local `controlnet.json` file afterwards.

**Comment by Danamir** [comment]
This should be alright now, be sure to remove the faulty `controlnet.json` file.
