### ISSUE TITLE
KeyError: 'controlnet_models'

### ISSUE THREAD

**Issue by GAC2099** [houseofsecrets/SdPaint#37]
![微信图片_20230429115608](https://user-images.githubusercontent.com/129135134/235282378-ae17bb13-45f2-4216-8e91-01d4d4f04fcf.png)
![微信截图_20230429115807](https://user-images.githubusercontent.com/129135134/235282472-c8234dce-8cbb-4840-b1a9-e079cceb4819.png)
The model was downloaded and placed in the corresponding folder, but an error occurred. I hope to receive guidance
Error loading script: SdPaint.py
Traceback (most recent call last):
  File "E:\JCZY\004sd-webui-aki-v4\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\JCZY\004sd-webui-aki-v4\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\JCZY\004sd-webui-aki-v4\extensions\SdPaint\scripts\SdPaint.py", line 174, in <module>
    if not config['controlnet_models']:
KeyError: 'controlnet_models'

**Comment by Danamir** [comment]
This issue will be fixed in the next batch of development. In the meantime you can use this file as your `config.json` : 

```
{
    "interface_width": 1280,
    "interface_height": 720,
    "url": "http://127.0.0.1:7860",
    "hr_scales": [
        1.25,
        1.5,
        2
    ],
    "hr_upscalers": [
        "Latent (bicubic)",
        "R-ESRGAN 4x+"
    ],
    "denoising_strengths": [
        0.6,
        0.4,
        0.5
    ],
    "controlnet_guidance_ends": [
        1.0,
        0.2,
        0.3
    ],
    "controlnet_weights": [
        0.6,
        1.0,
        1.6
    ],
    "controlnet_models": [],
    "detectors": [
        "lineart",
        "lineart_coarse",
        "pidinet_sketch",
        "pidinet_scribble"
    ],
    "samplers": [
        "DPM++ 2M Karras",
        "DDIM",
        "Euler",
        "Euler a",
        "DPM++ SDE Karras"
    ]
}
```
