### ISSUE TITLE
KeyError: 'Images'

### ISSUE THREAD

**Issue by ikbentheo** [houseofsecrets/SdPaint#4]
Got the following error after starting painting: 

`File "C:\Users\ikben\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\ikben\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\SdPaint-main\Scripts\SdPaint.py", line 92, in send_request
    return_img = r['images'][0]
KeyError: 'images'`

I enabled API mode and allowed controlnet.

**Comment by Lucavorenz** [comment]
Make sure the "--api" is in the .bat.
Install controlnet.

1. http://127.0.0.1:7860/
2. Extensions
3. Available
4. CLICK on "Load from:"
5. Search for "controlnet" and Click "Install"
6. Restart the UI and launch the SdPaint
**If you want to change prompts, styles, models, whatever - edit the "payload.json"

**Comment by EtherialAi** [comment]
I'm getting the same error as @ikbentheo
1) Just updated Auto1111 and Controlnet via git pull
2) --api is saved in webui-user.bat
3) "allow other scripts" checked - applied those settings and restarted UI
4) twirled open controlnet interface in Auto1111 webui, and checked "Enable" box
5) run SdPaint Start.bat
Canvas launches, but first stroke gives same error as above. Only difference is in the line# of the SdPaint.py:

`Desktop\SdPaint PyScript\SdPaint-main\Scripts\SdPaint.py", line 113, in send_request
    return_img = r['images'][0]
KeyError: 'images'`

What am I missing?
Thanks

**Comment by pineapple00** [comment]
I had this issue, and turns out I needed to update from Python 3.9 to 3.10.11! 
Sorry ikbentheo, since it doesn't seem to apply to you since you already seem to be on 3.10

**Comment by Danamir** [comment]
The API is receiving an empty model name. Can you try to delete your `config.json` and `controlnet.json` files, start the webui + API, and only when the webui is started start SdPaint. It should fetch your model names from http://127.0.0.1:7860/controlnet/model_list and write those in the newly created `config.json` (check the `controlnet_models` entry in the file).

**Comment by Danamir** [comment]
Or it could simply has something do to with the ControlNet side. I see that some of your `.safetensors` files have no `.yaml` pendant. Try to copy some of the yaml files with the corresponding filename.

**Comment by Danamir** [comment]
Oh and I just saw in your first picture that `/controlnet/txt2img` is called, you have an old version of SdPaint. Please do a `git pull` to get the latest one.

**Comment by jonasgrillo** [comment]
hey! when you told me to check the .json files, i realized that i didn't have them and then i saw that i actually cloned only half the code, several files were missing. i downloaded the repo again and now it works! :-) thanks for this awesome program!!
