### ISSUE TITLE
Canvas visibility problem

### ISSUE THREAD

**Issue by Thomixioso** [houseofsecrets/SdPaint#49]
Hello,

after succesful installation, when I paint someting in the right part of canvas, I see computing on the top of canvas, but dont see any image results on the left side of canvas. Just white.

**Comment by esbowman** [comment]
Exact same issue here. I'm hopeful someone can figure this out. I'd absolutely love to try this.

**Comment by Danamir** [comment]
Can you please check your logs for a Python error traceback, and copy it here.

**Comment by esbowman** [comment]
Not totally sure where to find that, but my cmd prompt is showing the following after making a brush stroke 

```
Error running process: C:\Users\Eric\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Eric\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "C:\Users\Eric\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1022, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "C:\Users\Eric\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 675, in load_control_model
    if model in Script.model_cache:
TypeError: unhashable type: 'list'
```

**Comment by Danamir** [comment]
This error is from the webui side. ControlNet is receiving a list where it was unexpected.

Could you check if this solves your problem : https://github.com/houseofsecrets/SdPaint/issues/50#issuecomment-1551739598

**Comment by esbowman** [comment]
Thank you. So i removed the config.json file found in the stable-diffusion-webui folder. I also removed SD Paint and reinstalled via the git hub link in the web ui extension list but still see the same errors.

**Comment by esbowman** [comment]
This is the list I see if I run the command from that comment:
`{"model_list":["control_v11e_sd15_ip2p [c4bb465c]","control_v11e_sd15_shuffle [526bfdae]","control_v11f1e_sd15_tile [a371b31b]","control_v11f1p_sd15_depth [cfd03158]","control_v11p_sd15_canny [d14c016b]","control_v11p_sd15_inpaint [ebff9138]","control_v11p_sd15_lineart [43d4be0d]","control_v11p_sd15_mlsd [aca30ff0]","control_v11p_sd15_normalbae [316696f1]","control_v11p_sd15_openpose [cab727d4]","control_v11p_sd15_scribble [d4ba51ff]","control_v11p_sd15_seg [e1f51eb9]","control_v11p_sd15_softedge [a8575a2a]","control_v11p_sd15s2_lineart_anime [3825e83e]"]}`

**Comment by esbowman** [comment]
Ah ha, disregard. Not sure what happened, but after reinstalling controlnet, deleting the config.json file, and reinstalling sdpaint I have it working.

**Comment by Danamir** [comment]
Glad to hear it.

I think that if SdPaint is started the first time without the API, it can produce an unusable `config.json` file.
