### ISSUE TITLE
Getting 

### ISSUE THREAD

**Issue by utkukocaman** [houseofsecrets/SdPaint#5]
When I check,  http://127.0.0.1:7860/controlnet/txt2img it returns with "{"detail":"Method Not Allowed"}" altough it is allowed in the settings. Then trying to draw and getting error like this:

ControlNet model control_sd15_scribble [fef5e48e] loaded.
Loading preprocessor: none
  0%|                                                                                           | 0/15 [00:01<?, ?it/s]
API error: POST: http://127.0.0.1:7860/controlnet/txt2img {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)'}
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Yapay Zeka\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py:94 in receive                    │
│                                                                                                                      │
│ C:\Yapay Zeka\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py:89 in receive_nowait             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Yapay Zeka\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next             │
│                                                                                                                      │
│ C:\Yapay Zeka\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py:114 in receive                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

**Comment by hapliniste** [comment]
For the "method not allowed", I guess you cannot use GET on this endpoint. POST without parameters give error 500 but I think it's normal

**Comment by houseofsecrets** [comment]
I don't know what that could be. Did you change the resolution in the json file?
You could also try updating controlnet and automatic1111
