### ISSUE TITLE
Great little app.   My experiances

### ISSUE THREAD

**Issue by MrKuenning** [houseofsecrets/SdPaint#6]
Thanks for writing this neat script.
I wanted to share the issue, I ran into trying to get it to work.

- The first one was the fact that my WebUI port is different.

I saw in the errors it was pointing to local 7860 and my webUI does not use that.  
Mine is also published through a reverse proxy to a URL   like   https://ai.domain.net

This was fixable, but not in the config file instead in the python file.  I recommend having a field where users can choose the URL of their WebUI in an easier to find location, such as the json file.

- The second issue, I ran into is it would only draw on image, this turned out to be a hardcoded scribble control net filename.

I have recently replaced all of my controlnet files with 1.1 versions and none of the names or hashes matched.

This was fixable in the Json file, but may not be an obvious fix.

It might be nice to have a first launch wizard asking what controlnet file to use and what URL.  Or maybe just have those as fields at the top of the window.

**Comment by houseofsecrets** [comment]
Yes maybe that is something I can add in the future.
In the extra folder is a text file with some names of different controlnet models including the new ones
